require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InsightsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Insight. As you add validations to Insight, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InsightsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all insights as @insights" do
      insight = Insight.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:insights)).to eq([insight])
    end
  end

  describe "GET show" do
    it "assigns the requested insight as @insight" do
      insight = Insight.create! valid_attributes
      get :show, {:id => insight.to_param}, valid_session
      expect(assigns(:insight)).to eq(insight)
    end
  end

  describe "GET new" do
    it "assigns a new insight as @insight" do
      get :new, {}, valid_session
      expect(assigns(:insight)).to be_a_new(Insight)
    end
  end

  describe "GET edit" do
    it "assigns the requested insight as @insight" do
      insight = Insight.create! valid_attributes
      get :edit, {:id => insight.to_param}, valid_session
      expect(assigns(:insight)).to eq(insight)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Insight" do
        expect {
          post :create, {:insight => valid_attributes}, valid_session
        }.to change(Insight, :count).by(1)
      end

      it "assigns a newly created insight as @insight" do
        post :create, {:insight => valid_attributes}, valid_session
        expect(assigns(:insight)).to be_a(Insight)
        expect(assigns(:insight)).to be_persisted
      end

      it "redirects to the created insight" do
        post :create, {:insight => valid_attributes}, valid_session
        expect(response).to redirect_to(Insight.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved insight as @insight" do
        post :create, {:insight => invalid_attributes}, valid_session
        expect(assigns(:insight)).to be_a_new(Insight)
      end

      it "re-renders the 'new' template" do
        post :create, {:insight => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested insight" do
        insight = Insight.create! valid_attributes
        put :update, {:id => insight.to_param, :insight => new_attributes}, valid_session
        insight.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested insight as @insight" do
        insight = Insight.create! valid_attributes
        put :update, {:id => insight.to_param, :insight => valid_attributes}, valid_session
        expect(assigns(:insight)).to eq(insight)
      end

      it "redirects to the insight" do
        insight = Insight.create! valid_attributes
        put :update, {:id => insight.to_param, :insight => valid_attributes}, valid_session
        expect(response).to redirect_to(insight)
      end
    end

    describe "with invalid params" do
      it "assigns the insight as @insight" do
        insight = Insight.create! valid_attributes
        put :update, {:id => insight.to_param, :insight => invalid_attributes}, valid_session
        expect(assigns(:insight)).to eq(insight)
      end

      it "re-renders the 'edit' template" do
        insight = Insight.create! valid_attributes
        put :update, {:id => insight.to_param, :insight => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested insight" do
      insight = Insight.create! valid_attributes
      expect {
        delete :destroy, {:id => insight.to_param}, valid_session
      }.to change(Insight, :count).by(-1)
    end

    it "redirects to the insights list" do
      insight = Insight.create! valid_attributes
      delete :destroy, {:id => insight.to_param}, valid_session
      expect(response).to redirect_to(insights_url)
    end
  end

end
